# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x5nC5BGABFo0yE1agqfOQQzm5fhf4mCY
"""

from sklearn.linear_model import LogisticRegression
import numpy as np

# Training data (X: keyword counts, y: spam or not)
X_train = np.array([[2], [5], [8], [12]])
y_train = np.array([0, 0, 1, 1])

# Fit logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict probability of being spam for a new email with 7 keywords
probability_of_spam = model.predict_proba(np.array([[7]]))[:, 1]

print(probability_of_spam)